#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#xclock -geometry 50x50-1+1 &
#sudo rfkill unblock wifi
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/local/bin/status &
#goblocks &!
nitrogen --restore &
xcompmgr &
setxkbmap br
/usr/bin/light -S 55.00

#( sleep 1s && bash /usr/local/bin/lemonbar.sh | lemonbar -p -F#6f20a5 -B#020006 -f "Dejavu Sans Mono Nerd Font"-16 -f FontAwesome5-16) &

exec dwm


#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login
